### ISSUE TITLE
FR: Option to remove all scoping

### ISSUE THREAD

**Issue by mnestor** [jamfprofessionalservices/JamfMigrator#16]
When migrating specific items to another JSS it would be nice if there was an option to remove all scoping so the policy/profile/etc came into the new JSS and didn't immediately apply to systems.

**Comment by canalnoises** [comment]
I agree that it would be helpful to not have migrated items apply immediately. I think it would be better though to disable the item instead of removing the scope. If the scoping is complicated I really want it to come over when I migrate the policy from stage to production so I don't have to redo it and risk doing something different from what I tested.

**Comment by scheblein** [comment]
+1 - this breaks so many of my migrations because the scoping doesn't match "exactly". I don't need an exact match when refreshing my dev/test instance from prod.

**Comment by BIG-RAT** [comment]
Beta posted in releases (https://github.com/jamfprofessionalservices/JamfMigrator/releases).
<img width="204" alt="migrator_prefs_sm" src="https://user-images.githubusercontent.com/22251543/40933792-a01f02fa-6800-11e8-8e29-07590a93b994.png">
